# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
import numpy as np
np.__version__

'1.21.2'

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
import numpy as np
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
x=np.zeros((5,5))
print(x.size*x.itemsize)

200


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
import numpy as np
a=np.arange(9)
print(np.info(a))

class:  ndarray
shape:  (9,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x1de68eb2270
byteorder:  little
byteswap:  False
type: int32
None


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
import numpy as np
a=np.zeros(9)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
import numpy as np
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [8]:
import numpy as np
a=np.arange(10,50)
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [9]:
import numpy as np
a=np.arange(9)
b=a.reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [10]:
import numpy as np
a=[1,2,0,0,4,0]
print(np.nonzero(a))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [11]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [12]:
import numpy as np
print(np.random.rand(3,3,3))

[[[0.93921082 0.03390859 0.05002751]
  [0.99051778 0.4325152  0.47039087]
  [0.58152669 0.50485607 0.63652384]]

 [[0.16908801 0.07974865 0.4648153 ]
  [0.87926243 0.72946371 0.80215772]
  [0.97866096 0.82424478 0.41561793]]

 [[0.94886423 0.83749822 0.37620685]
  [0.63450492 0.24433001 0.08395033]
  [0.70826619 0.70240266 0.20683778]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [13]:
import numpy as np
a=np.random.rand(10,10)
print(a)

print("Maximum value:", a.max())
print("Minimum value:", a.min())

[[0.45774993 0.44048431 0.8536057  0.97227581 0.31563173 0.77948191
  0.99385136 0.20100883 0.98642572 0.63949869]
 [0.62374999 0.39036082 0.94200367 0.71406047 0.92038039 0.54469042
  0.5599657  0.54086775 0.41565499 0.55237594]
 [0.36728848 0.3807828  0.36988335 0.67924105 0.15527912 0.27192152
  0.73988594 0.0892604  0.44510377 0.95719486]
 [0.75217064 0.56099891 0.67950683 0.66705147 0.10371667 0.70674911
  0.93941644 0.2837391  0.14283584 0.21629524]
 [0.61442309 0.8439732  0.51660494 0.35478409 0.21752032 0.25701907
  0.05517422 0.4454736  0.94813167 0.54323811]
 [0.24674203 0.4105538  0.02439915 0.85210799 0.30566022 0.7672179
  0.28248901 0.35475939 0.36088362 0.41240744]
 [0.09796242 0.219847   0.11670329 0.01292392 0.31170906 0.52365991
  0.17768854 0.87642991 0.93494983 0.72472496]
 [0.39089261 0.95838866 0.96602573 0.49681172 0.771078   0.4990485
  0.20921853 0.74184459 0.29871747 0.70448615]
 [0.36008211 0.54210159 0.74114423 0.11503815 0.88813694 0.92958321
  0.48979542 0

 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(hint: mean)

In [14]:
import numpy as np
a=np.random.rand(30)
print(a)
print("Mean:", a.mean())

[0.41373038 0.98120484 0.16758687 0.15674701 0.54735678 0.0609889
 0.37626969 0.40636064 0.50221891 0.57767204 0.03250783 0.83947711
 0.28412156 0.71138309 0.80497272 0.19501378 0.29135862 0.16007812
 0.42685205 0.06997684 0.48786869 0.04983376 0.41621671 0.03817738
 0.91738449 0.82465078 0.96348663 0.47828668 0.66362572 0.43731253]
Mean: 0.4427573712565189


 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(hint: array\[1:-1, 1:-1\])

In [15]:
import numpy as np
a=np.ones((5,5))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [16]:
import numpy as np
a=np.random.rand(4,4)
a=np.pad(a,pad_width=1,constant_values=0)
print(a)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.70999803 0.95657809 0.78915253 0.31913263 0.        ]
 [0.         0.16521996 0.71209799 0.27543341 0.39734869 0.        ]
 [0.         0.12578817 0.93972977 0.7505906  0.62352897 0.        ]
 [0.         0.08507651 0.31438249 0.09984037 0.80358996 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [17]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


In [ ]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(hint: np.diag)

In [18]:
import numpy as np
x=np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [19]:
import numpy as np
a=np.ones((3,3))
a=np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [20]:
import numpy as np
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [21]:
import numpy as np
z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [22]:
import numpy as np
z=np.random.random((5,5))
z=(z-np.min(z))/(np.max(z)-np.min(z))
print(z)

[[0.69536436 0.44856199 0.56539288 0.55633212 0.30695051]
 [0.69281241 0.76905049 0.45588816 0.18217529 0.82335748]
 [0.         0.53094008 0.75762591 0.57082925 0.03328508]
 [0.58264234 0.25913809 1.         0.59214107 0.82605696]
 [0.78981433 0.50358    0.12994925 0.31981595 0.03634059]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [23]:
color=np.dtype([('r',np.ubyte),
               ('g',np.ubyte),
               ('b',np.ubyte),
               ('a',np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [24]:
import numpy as np
M1=np.array([[3, 6, 9], [5, -10, 15], [-7, 14, 21],[2,-4,6],[1,-3,7]])
M2=np.array([[1,-3],[2,-4],[3,-5]])
M3=M1.dot(M2)
print(M3)

[[  42  -78]
 [  30  -50]
 [  84 -140]
 [  12  -20]
 [  16  -26]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [25]:
import numpy as np
a=np.arange(9)
a[3:9] = np.multiply(a[3:9],-1)
print(a)

[ 0  1  2 -3 -4 -5 -6 -7 -8]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
Z=1
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

False

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Sindhu\AppData\Local\Temp/ipykernel_768/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\Sindhu\AppData\Local\Temp/ipykernel_768/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [29]:
import numpy as np
x=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(x)),x))
print(np.where(x>0,np.ceil(x),np.floor(x)))

[-2.  6. -9. -8. -5. -7. -3. -1.  2.  8.]
[-2.  6. -9. -8. -5. -7. -3. -1.  2.  8.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [30]:
arr=np.array([10,20,30,40,50,60])
arr1=np.array([10,70,80,90,100])
print(np.intersect1d(arr,arr1))

[10]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [31]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


C:\Users\Sindhu\AppData\Local\Temp/ipykernel_768/2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [32]:
yesterday=np.datetime64('today') - np.timedelta64(1)
today=np.datetime64('today')
tomorrow=np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2021-09-26
2021-09-27
2021-09-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [33]:
a=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [34]:
A=np.ones(3)*1
B=np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [35]:
import numpy as np
x=np.random.uniform(0,10,10)
print(x-x%1)
print(np.floor(x))
print(np.ceil(x))
print(x.astype(int))
print(np.trunc(x))

[2. 0. 2. 3. 7. 9. 7. 8. 6. 4.]
[2. 0. 2. 3. 7. 9. 7. 8. 6. 4.]
[ 3.  1.  3.  4.  8. 10.  8.  9.  7.  5.]
[2 0 2 3 7 9 7 8 6 4]
[2. 0. 2. 3. 7. 9. 7. 8. 6. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [36]:
A=np.tile(np.arange(0,5),(5,1))
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [37]:
def generate():
    for x in range(10):
        yield x
z=np.fromiter(generate(),dtype=float)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [39]:
x=np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [40]:
import numpy as np
A=np.random.rand(10)
print(sort(A))

[0.10241479 0.11875435 0.13400079 0.20980119 0.23467753 0.35939507
 0.38426035 0.3892023  0.557518   0.98792268]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [41]:
import numpy as np
A=np.random.rand(10)
print(np.add.reduce(A))

3.8832805839821734


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [42]:
import numpy as np
a=np.ones(10)
b=np.ones(10)
print(np.array_equal(a,b))

True


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [43]:
import numpy as np
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.61779183 0.78550608 0.62952265 1.21074609 0.43811891 0.33872918
 0.6023609  1.18991311 0.99889414 0.91591302]
[0.59414054 0.69079423 0.63880888 0.65295289 0.94885143 1.24315343
 0.62635773 0.97152159 0.42937247 0.29058165]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [44]:
import numpy as np
arr=np.arange(9)
arr[arr.argmax()]=0
print(arr)

[0 1 2 3 4 5 6 7 0]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [18]:
c=np.zeros((5,5),[('x',float),('y',float)])
c['x'],c['y']=np.meshgrid(np.linspace(0,1,5),
                         np.linspace(0,1,5))
print(c)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [45]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [20]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [51]:
np.set_printoptions(threshold=float("inf"))
x = np.zeros((10,10))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [50]:
x = np.arange(100)
y = np.random.uniform(0,100)
index = (np.abs(x-y)).argmin()
print(x[index])

35


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [49]:
x = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Sindhu\AppData\Local\Temp/ipykernel_768/2893404235.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
import numpy as np
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [52]:
x = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(x):
    print(index, value)
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [53]:
n = 10
p = 3
x = np.zeros((n,n))
np.put(x, np.random.choice(range(n*n), p, replace=False),1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [54]:
import numpy as np
x=np.random.rand(5,10)
y=x-x.mean(axis=1,keepdims=True)
y=x-x.mean(axis=1).reshape(-1,1)
print(y)

[[ 2.30458822e-01 -1.55043195e-01 -2.34755290e-01  1.53833341e-01
  -2.46865659e-01  5.79648905e-01 -1.26260414e-01  3.15904414e-02
  -1.02950904e-01 -1.29656048e-01]
 [ 4.22384486e-01 -2.92015899e-01  2.24023202e-01 -3.92095124e-02
  -9.44441803e-05  7.28613624e-02 -3.38128063e-01 -4.29066617e-01
   3.76857495e-01  2.38799173e-03]
 [ 4.75499271e-02  3.18035664e-01  3.87699281e-01 -1.75222003e-02
   1.23050301e-02 -1.21602931e-01  1.46175657e-01 -4.66844658e-01
  -5.31937143e-01  2.26141374e-01]
 [ 1.26289670e-01 -8.22364878e-02 -2.44055588e-01 -9.62823802e-02
   1.59453766e-01 -1.07736523e-02 -1.14331830e-01 -1.05544903e-01
   6.00967550e-02  3.07384651e-01]
 [-4.02431966e-02 -2.34228674e-01 -9.61431337e-02  1.58544353e-02
   2.27518226e-01 -4.90168991e-01  4.32466779e-01 -3.98813372e-02
  -1.26867578e-02  2.37512651e-01]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [55]:
x = np.random.randint(0,10,(3,3))
print(x)
print(x[x[:,1].argsort()])

[[3 2 2]
 [0 0 8]
 [4 7 0]]
[[0 0 8]
 [3 2 2]
 [4 7 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [56]:
x = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())
print(x)

False
[[0 0 2 0 0 0 0 1 0 1]
 [2 1 1 1 0 0 2 1 0 2]
 [0 0 2 1 1 0 0 0 2 2]]


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [57]:
x = np.random.uniform(0,1,10)
z = 0.5
m = x.flat[np.abs(x - z).argmin()]
print(m)

0.6467988206200915


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [58]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [3]:
import numpy as np
X = [1,2,3,4,5,6]
I = [1,3,5,7,9,11]
F = np.bincount(I,X)
print(F)

[0. 1. 0. 2. 0. 3. 0. 4. 0. 5. 0. 6.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [5]:
x=np.array([1,2,3,4,5])
nx=3
z0=np.zeros(len(x)+(len(x)-1)*(nx))
z0[::nx+1] = x
print(z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [7]:
a=np.ones((5,5,3))
b=5*np.ones((5,5))
print(a*b[:,:,None])

[[[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [8]:
A=np.arange(9).reshape(3,3)
A[[0,1]] = A[[1,0]]
print(A)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [9]:
import numpy as np
C=np.bincount([1,2,3,4,5,6,7])
a=np.repeat(np.arange(len(C)),C)
print(a)

[1 2 3 4 5 6 7]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [11]:
x=np.random.randint(0,2,10)
np.logical_not(x,out=x)
x1=np.random.uniform(-1.0,1.0,10)
np.negative(x1,out=x1)

array([ 0.47745525, -0.48401376,  0.60594759, -0.42369274, -0.35713068,
       -0.6810337 ,  0.63577625, -0.25272309, -0.27847157, -0.70248738])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [13]:
x=np.random.randint(0,5,10)
print(np.bincount(x).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [17]:
x=np.arange(10000)
np.random.shuffle(x)
n=5
print(x[np.argsort(x)[-n:]])
print(x[np.argpartition(-x,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9996 9995 9997]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)